Repository WebUI-Project-Based-10-nr/Client, pull requests merged in 2024-11, with the labels that each got.

#169 Feature/27/impl add photo step
  src/components/user-steps-wrapper/UserStepsWrapper.tsx
  src/constants/translations/en/become-tutor.json
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.jsx
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.style.js
  src/containers/tutor-home-page/add-photo-step/fileHandlers.ts
  src/containers/tutor-home-page/add-photo-step/utils.ts
Labels: Frontend part, feature, sprint 4

#167 Feature/10/implement stepper location
  .gitignore
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
Labels: Frontend part, feature, sprint 3

#171 Feature/17/add button and chips
  src/containers/tutor-home-page/subjects-step/SubjectsStep.styles.js
  src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx
  src/context/step-context.jsx
  src/context/step-context.tsx
  src/styles/app-theme/app.pallete.ts
Labels: Frontend part, feature, sprint 3

#172 (SP: 1) [Categories] Implement "Create request" block #34
  src/constants/translations/en/find-offer-page.json
  src/constants/translations/ua/find-offer-page.json
  src/containers/find-offer/constants.ts
  src/containers/find-offer/create-offer-request/CreateOfferRequest.tsx
  src/containers/find-offer/offer-request-block/OfferRequestBlock.tsx
  src/pages/categories/Categories.tsx
Labels: Frontend part

#182 Implement offer card (wide and square versions)
  src/components/offer-card/buttons/SendMessageButton.tsx
  src/components/offer-card/buttons/ViewDetailsButton.tsx
  src/components/offer-card/buttons/bookmark-button/BookmarkButton.styles.ts
  src/components/offer-card/buttons/bookmark-button/BookmarkButton.tsx
  src/components/offer-card/offer-card-narrow/OfferCardNarrow.styles.ts
  src/components/offer-card/offer-card-narrow/OfferCardNarrow.tsx
  src/components/offer-card/offer-card-wide/OfferCardWide.styles.ts
  src/components/offer-card/offer-card-wide/OfferCardWide.tsx
  src/components/offer-card/offer-card-wide/offer-details/OfferDetails.styles.ts
  src/components/offer-card/offer-card-wide/offer-details/OfferDetails.tsx
  src/components/offer-card/price/Price.tsx
  src/tests/unit/components/offer-card/OfferCard.spec.jsx
  src/tests/unit/components/offer-card/buttons/BookmarkButton.spec.jsx
Labels: Frontend part

#187 Implement "Frequently asked questions" block
  src/containers/student-home-page/faq/Faq.tsx
Labels: Frontend part, feature

#186 [Find offers] Make a container for cards
  src/components/offer-card/offer-card-narrow/OfferCardNarrow.styles.ts
  src/components/offer-card/offer-card-narrow/OfferCardNarrow.tsx
  src/components/offer-card/offer-card-wide/OfferCardWide.styles.ts
  src/containers/find-offer/offer-cards-container/OfferCardsContainer.tsx
  src/containers/find-offer/offer-cards-container/grid-offers/GridOffers.styles.ts
  src/containers/find-offer/offer-cards-container/grid-offers/GridOffers.tsx
  src/containers/find-offer/offer-cards-container/list-offers/ListOffers.tsx
  src/tests/unit/containers/offer-cards-container/GridOffers.spec.jsx
  src/tests/unit/containers/offer-cards-container/ListOffers.spec.jsx
  src/tests/unit/containers/offer-cards-container/OfferCardsContainer.spec.jsx
  src/types/find-offers/findOffers.index.ts
  src/types/find-offers/types/findOffers.types.ts
  src/types/index.ts
Labels: Frontend part

#191 [Find offers] Add view switcher
  src/components/view-switcher/ViewSwitcher.styles.ts
  src/components/view-switcher/ViewSwitcher.tsx
  src/components/view-switcher/icon-button/IconButton.styles.ts
  src/components/view-switcher/icon-button/IconButton.tsx
  src/pages/find-offers/FindOffers.styles.ts
  src/pages/find-offers/FindOffers.tsx
  src/tests/unit/components/view-switcher/ViewSwitcher.spec.jsx
Labels: Frontend part
