Repository WebUI-Project-Based-10-nr/Client, pull requests merged in 2024-10, with the labels that each got.

#120 Set up SonarCloud client integration
  sonar-project.properties
Labels: Frontend part, feature

#125 Write tests for enhanced table pagination component
  src/tests/unit/components/enhanced-table/enhanced-table-pagination/EnhancedTablePagination.spec.jsx
Labels: sprint 2, test

#150 add lesson interface to fix eslint error in AddLessons component
  src/types/my-resources/interfaces/myResources.interface.ts
Labels: bug, Frontend part, sprint 2

#152 Resolve ESLint error in CreateOrEditQuestionModal component
  src/containers/my-resources/create-or-edit-question-modal/CreateOrEditQuestionModal.tsx
Labels: bug, Frontend part, sprint 2

#142 Add unit test for QuestionEditor component
  src/tests/unit/components/question-editor/QuestionEditor.spec.jsx
Labels: Frontend part, sprint 2, test

#145 Fix question item description
  src/containers/my-resources/questions-container/QuestionsContainer.constants.tsx
Labels: bug, Frontend part, sprint 2

#133 Write tests for content switcher component
  src/tests/unit/components/app-content-switcher/AppContentSwitcher.spec.jsx
Labels: sprint 2, test

#135 Write tests for search filter input component
  src/tests/unit/components/search-filter-input/SearchFilterInput.spec.jsx
Labels: sprint 2, test

#140 [Become a student pop-up] The description is not corresponded to the mockup in the “Photo” page
  src/constants/translations/en/become-tutor.json
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.jsx
Labels: bug, Frontend part

#139 [Mentor 'Sign Up' pop-up] the text "Already have a Space2Study account? Log In" doesn't correspond the requirements
  src/constants/translations/en/signup.json
Labels: bug, Frontend part, sprint 2

#156 fix eslint for link component
  src/types/common/types/common.types.ts
Labels: bug, Frontend part, sprint 2

#153 Write tests for enhanced table row component
  src/tests/unit/components/enhanced-table/enhanced-table-row/EnhancedTableRow.spec.jsx
Labels: Frontend part, sprint 2, test

#158 Add closing modular window
  src/components/popup-dialog/PopupDialog.styles.ts
  src/components/popup-dialog/PopupDialog.tsx
Labels: Frontend part, feature, sprint 3

#159 (SP: 1) Add photo and select on Subjects step
  src/components/user-steps-wrapper/UserStepsWrapper.tsx
  src/constants/translations/en/become-tutor.json
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.styles.js
  src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx
Labels: Frontend part, feature, sprint 3

#161 Add Interests step to student stepper
  src/components/user-steps-wrapper/UserStepsWrapper.tsx
  src/components/user-steps-wrapper/constants.ts
Labels: Frontend part

#163 Implement language selection
  src/components/step-image/StepImage.styles.js
  src/components/step-image/StepImage.tsx
  src/constants/translations/en/become-tutor.json
  src/containers/tutor-home-page/language-step/LanguageStep.jsx
  src/containers/tutor-home-page/language-step/LanguageStep.styles.js
  src/containers/tutor-home-page/language-step/constants.ts
Labels: Frontend part

#166 Add PopupDialog,tsx
  src/components/popup-dialog/PopupDialog.styles.ts
Labels: bug, Frontend part

#168 Implement "Sorry, no results found" block
  src/pages/categories/Categories.tsx
Labels: Frontend part
